### ISSUE TITLE
[Research] Terminal Info

### ISSUE THREAD

**Issue by HiceS** [RE-Capstone/ConsoleTester#3]
## Topic

Terminal Information will need to be researched to begin with and how it can be accessed through Rust. I would start by investigating how ` TermInfo ` works and possibly watch some tutorials on how terminal delimiters work.

This isn't limited to terminfo, instead come up with a action plan about how we can build a system to determine the local users terminal info and how that terminal parses input.

### Solving issue
1. Create a new branch.
2. Determine what are the deliverable listed below.
3. Investigate issue or topic.
4. Create in code example to demonstrate knowledge using a branch labeled Research-[issue number].
5. Create simple slide deck or paper to explain to others on the team what you have learned.
6. Give a suggested course of action during the retrospective.

### Definition of Done

- [ ] Example Code Works
- [ ] Continuous Integration Passes
- [ ] Code is integrated into Master (if applicable)
- [ ] Unit Tests are created

### Links

[ List of acceptable links for research topic ]
 - [linux man page](https://linux.die.net/man/5/terminfo)

### Examples

[ List of other research topic examples of links to other repos ]

### PR

[ Link to Pull Request ]

**Comment by HiceS** [comment]
https://docs.rs/tinf/0.14.0/tinf/

**Comment by HiceS** [comment]
https://stebalien.github.io/doc/term/term/

**Comment by b-hopper** [comment]
https://docs.rs/terminfo/0.7.2/terminfo/

This crate contains full terminfo capability.

(From proposal document)
![image](https://user-images.githubusercontent.com/12116209/81994266-4af3a480-95fc-11ea-9927-35a6dbd931bd.png)

The information seen in that screenshot is a list of delimiters and terminal information and capabilities. This information can be accessed through the Rust crate terminfo using the following:

```
use terminfo::*;

fn main() {
    let mut info = Database::from_env().unwrap();

    info.name();         // Terminal name, stored in &str
    info.description();  // Terminal description, &str
    
    let colors: i32 = std::convert::Into::into(info.get::<capability::MaxColors>().unwrap();
        // Number value capability, in this case the terminal's max colors
    let mut charset = info.raw("ac").unwrap();
        // Getting raw capability information by termcap name
        // This example gets the charset information (aA-zZ)
        // Stored in Value struct

    match &charset {
        capability::Value::True => println!("True"),
        capability::Value::Number(n) => println!("Number: {}", n),
        capability::Value::String(s) => println!("String: {:?}", s)
    }  // Accessing members of Value struct
}
```

List of terminfo variable names (as well as their termcap and cap-name variants) and types found here: https://pubs.opengroup.org/onlinepubs/007908799/xcurses/terminfo.html
