### ISSUE TITLE
[Research]  Cratesio deployment

### ISSUE THREAD

**Issue by HiceS** [RE-Capstone/ConsoleTester#6]
## Topic

We need this project to be deployable as a crate to developers who want to use it. I do not have much experience with this so I need someone to look into what is required of us and how we can integrate that requirement with our Travis Continuous Integration.

If needed I can add post-build scripts to upload built code as an example.

### Solving issue
1. Create a new branch.
2. Determine what are the deliverable listed below.
3. Investigate issue or topic.
4. Create in code example to demonstrate knowledge using a branch labeled Research-[issue number].
5. Create simple slide deck or paper to explain to others on the team what you have learned.
6. Give a suggested course of action during the retrospective.

### Definition of Done

- [ ] Example Code Works
- [ ] Continuous Integration Passes
- [ ] Code is integrated into Master (if applicable)
- [ ] Unit Tests are created

### Links

[ List of acceptable links for research topic ]
- [Link to documentation ](https://doc.rust-lang.org/cargo/guide/creating-a-new-project.html)
- [crates website](https://crates.io/)

- [note1](https://github.com/Spotifyd/spotifyd/issues/462)
- [note2 rabbithole](https://github.com/rust-lang/cargo/issues/6153)

### Examples

[ List of other research topic examples of links to other repos ]
- [example crate](https://crates.io/crates/leap-sys)
- [example github for crate](https://github.com/urholaukkarinen/leap-sys)
- [example gh ci](https://github.com/Spotifyd/spotifyd/tree/master/.github/workflows)

### PR

[ Link to Pull Request ]

**Comment by igaul** [comment]
Wait until mvp.
